version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:11.0.2-jdk-stretch
    working_directory: ~/logmatters

    steps:
    - checkout
    - setup_remote_docker
    - deploy:
        name: maven build
        command: |
              java -version
              mvn --version
              mvn clean package --quiet
    - deploy:
        name: docker push
        command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              export TAG=latest
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              docker build -t dashbase/logmatters:$TAG .
              docker push dashbase/logmatters:$TAG
              docker tag  dashbase/logmatters:$TAG dashbase/logmatters:$TAG-${CIRCLE_SHA1::6}
              docker push dashbase/logmatters:$TAG-${CIRCLE_SHA1::6}
              .circleci/update.sh
            fi