version: 2
jobs:
  build:
    docker:
    - image: circleci/buildpack-deps:curl
    working_directory: ~/logmatters

    steps:
    - checkout
    - setup_remote_docker


    - deploy:
        command: |
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker build . -t dashbase/logmatters
          docker login
          docker push dashbase/logmatters
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo 1
          fi
