version: 2
jobs:
  build:
    docker:
    - image: circleci/buildpack-deps:curl
    working_directory: ~/logmatters

    steps:
    - checkout
    - setup_remote_docker


    - deploy:
        command: |
          export TAG=latest
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          docker build -t dashbase/logmatters:$TAG .
          docker push dashbase/logmatters:$TAG

          docker build -t dashbase/logmatters:$TAG-${CIRCLE_SHA1::6} .
          docker push dashbase/logmatters:$TAG-${CIRCLE_SHA1::6}

          .circleci/update.sh

          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            echo 1
          fi
