services:
  web:
    sla: 99.9
    latencyMs:
      p50: 80
      p90: 100
      p99: 500
  registration:
    sla: 10
    latencyMs:
      p50: 10
      p90: 50
      p99: 200
  mysql:
    sla: 90
    latencyMs:
      p50: 50
      p90: 100
      p99: 500
  billing:
    sla: 90
    latencyMs:
      p50: 40
      p90: 200
      p99: 1000
  kafka:
    sla: 95
    latencyMs:
      p50: 50
      p90: 100
      p99: 500

deployment:
    concurrentRequest: 100
    callPath:
      concurrent: true
      services:
          - web:
              concurrent: false
              services:
                - registration:
                    concurrent: true
                    services:
                      - mysql:
                          concurrent: false
                      - kafka:
                          concurrent: false

server:
  applicationConnectors:
    - type: http
      port: 0
  adminConnectors:
    - type: http
      port: 0

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: logs/logmatters.log
        archive: true
        archivedLogFilenamePattern: logs/logmatters-%d.log.%i
        archivedFileCount: 7
        timeZone: UTC
        maxFileSize: 10MB