throttleNPerSec: -1

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: logs/logmatters.log
        archive: true
        archivedLogFilenamePattern: logs/logmatters-%d.log.%i
        archivedFileCount: 7
        timeZone: UTC
        maxFileSize: 200MB
        logFormat: "%-5p [%d{ISO8601}] %c: %replace(%msg){'[\r\n]+','\\\\n'} %replace(%ex){'[\r\n]+', '\\\\n'}%nopex%n"
      #- type: console
       # logFormat: "%-5p [%d{ISO8601}] %c: %replace(%msg){'[\r\n]+','\\\\n'} %replace(%ex){'[\r\n]+', '\\\\n'}%nopex%n"
