throttleNPerSec: 1

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
      - type: file
        currentLogFilename: logs/logmatters.log
        archive: true
        archivedLogFilenamePattern: logs/logmatters-%d.log.%i
        archivedFileCount: 7
        timeZone: UTC
        maxFileSize: 10MB
        logFormat: "%-5p [%d{ISO8601}] %c: %replace(%msg){'[\r\n]+','\\\\n'} %replace(%ex){'[\r\n]+', '\\\\n'}%nopex%n"
      #- type: console
       # logFormat: "%-5p [%d{ISO8601}] %c: %replace(%msg){'[\r\n]+','\\\\n'} %replace(%ex){'[\r\n]+', '\\\\n'}%nopex%n"
